In [2]:
import pandas as pd

# Table 1: Student names + IDs
students = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Tariq', 'Sadiq', 'Rafiq', 'Sadaf']
})

# Table 2: Student IDs + Marks
marks = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Marks': [88, 92, 86, 99]
})

students

   ID   Name
0   1  Tariq
1   2  Sadiq
2   3  Rafiq
3   4  Sadaf

marks

In [4]:
full_data = pd.merge(students, marks, on='ID')
full_data

   ID   Name  Marks
0   1  Tariq     88
1   2  Sadiq     92
2   3  Rafiq     86
3   4  Sadaf     99

In [5]:
full_data.shape

(4, 3)

In [2]:
import pandas as pd

# Table 1: Student names + IDs
students = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Tariq', 'Sadiq', 'Rafiq', 'Sadaf']
})

# Table 2: Student IDs + Marks
marks = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Marks': [88, 92, 86, 99]
})

students

   ID   Name
0   1  Tariq
1   2  Sadiq
2   3  Rafiq
3   4  Sadaf

In [3]:
full_data = pd.merge(students, marks, on='ID')
full_data

   ID   Name  Marks
0   1  Tariq     88
1   2  Sadiq     92
2   3  Rafiq     86
3   4  Sadaf     99

In [4]:
full_data.shape

(4, 3)

In [6]:
import pandas as pd

In [9]:
students = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Tariq', 'Sadiq', 'Rafiq', 'Sadaf']
})

marks = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Marks': [88, 92, 86, 99]
})

full_data = pd.merge(students, marks, on='ID')
full_data

   ID   Name  Marks
0   1  Tariq     88
1   2  Sadiq     92
2   3  Rafiq     86
3   4  Sadaf     99

In [10]:
# Add Asif who has no marks
students = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5],
    'Name': ['Tariq', 'Sadiq', 'Rafiq', 'Sadaf', 'Asif']
})

marks = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Marks' : [88, 92, 86, 99]
})

# Default merge = inner
pd.merge(students, marks, on='ID')

   ID   Name  Marks
0   1  Tariq     88
1   2  Sadiq     92
2   3  Rafiq     86
3   4  Sadaf     99

In [11]:
pd.merge(students, marks, on='ID', how='left')

   ID   Name  Marks
0   1  Tariq   88.0
1   2  Sadiq   92.0
2   3  Rafiq   86.0
3   4  Sadaf   99.0
4   5   Asif    NaN

In [12]:
pd.merge(students, marks, on='ID', how='inner')

   ID   Name  Marks
0   1  Tariq     88
1   2  Sadiq     92
2   3  Rafiq     86
3   4  Sadaf     99

In [13]:
pd.merge(students, marks, on='ID', how='right')

   ID   Name  Marks
0   1  Tariq     88
1   2  Sadiq     92
2   3  Rafiq     86
3   4  Sadaf     99

In [14]:
pd.merge(students, marks, on='ID', how='outer')

   ID   Name  Marks
0   1  Tariq   88.0
1   2  Sadiq   92.0
2   3  Rafiq   86.0
3   4  Sadaf   99.0
4   5   Asif    NaN

In [25]:
batch1 = pd.DataFrame({'Prompt': ['Q1', 'Q2']})
batch2 = pd.DataFrame({'Prompt': ['Q3', 'Q4']})

all_Prompt = pd.concat([batch1, batch2])
# not the [] list
all_Prompt

  Prompt
0     Q1
1     Q2
0     Q3
1     Q4

In [26]:
all_Prompts = pd.concat([batch1, batch2])

In [27]:
all_Prompts.columns

Index(['Prompt'], dtype='object')